spring.application.name=ai
jwt.secret=sua_chave_secreta_base64_bem_longa_aqui
jwt.expiration=900000
jwt.refresh.expiration=86400000

spring.datasource.url=jdbc:postgresql://localhost:5432/dev_db
spring.datasource.username=postgres
spring.datasource.password=123


spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.boot.allow_jdbc_metadata_access=true

logging.level.root=INFO
logging.level.org.hibernate.SQL=WARN
logging.level.com.zaxxer.hikari=INFO
logging.level.br.com.yomu.gamificacaoDaLeitura=INFO